LOCAL_PATH:= $(call my-dir)
include $(CLEAR_VARS)
LOCAL_MODULE_TAGS := optional

LOCAL_RRO_THEME := SwitchMD2
LOCAL_PACKAGE_NAME := SwitchMD2
LOCAL_SDK_VERSION := current
LOCAL_CERTIFICATE := platform
LOCAL_PRIVILEGED_MODULE := false
LOCAL_PRODUCT_MODULE := true
include $(BUILD_RRO_PACKAGE)
